### ISSUE TITLE
Authorize Mitch's AWS account to access the internal WIM bucket on S3

### ISSUE THREAD

**Issue by mitch-wim** [USGS-WiM/science-planning#1]
This Science Planning project is internal, and I don't have access to the internal S3 bucket.

**Comment by HansVraga** [comment]
He needs access by Tuesday AM - so this should be done by Monday (19 Mar)

**Comment by aaronstephenson** [comment]
Guys, I don't get any notifications unless you assign me. So please do that in the future.

**Comment by aaronstephenson** [comment]
Mitch has access now.
