### ISSUE TITLE
Enhance Confluence Integration

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/science-planning#7]
- [x] Add Space to confluence

- [x] Add "communication updates" pages for Executives, Program Coordinators, Budget Planning, and Center Directors

- [x] Hit Confluence API to populate those sections of the tabs

- [ ] On page Account for any delay in loading of content

- [ ] On page Account for possibility of having no content

- [x] On page Account for possibility of confluence API being down/unresponsive (no response or error response)

- [ ] (might be a stretch) On page, Account for possibility of content not being updated for the new Year. (review 'last edited' fields)

**Comment by HansVraga** [comment]
I've put in the request to create the space...

**Comment by HansVraga** [comment]
Space Created, permissions updated, and pages created. Passing your way Mitch!

**Comment by HansVraga** [comment]
Confluence integration is in good shape for initial release. Tagging this as 'enhancement' in case we want to revisit in future efforts.

**Comment by mitch-wim** [comment]
May be helpful for myself later: https://www.sitepoint.com/working-around-origin-policy/

**Comment by HansVraga** [comment]
Work on this project complete.
